id: P004364
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG09729
  title: བོད་སིལ་བུའི་བྱུང་བ་བརྗོད་པ་ཤེལ་དཀར་ཕྲེང་བ་
  author: ''
  volumes:
    8a48219e950f4a09ba1a161dd284542e:
      image_group_id: I00KG09772
      title: ''
      volume_number: 1
      total_pages: 470
      base_file: v001.txt
